//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_64131375.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class CTHoaDon
    {
        [Key]
        [Column(Order = 0)]
        public string MaHD { get; set; }

        [Key]
        [Column(Order = 1)]
        public string MaSua { get; set; }
        //public string MaHD { get; set; }
        //public string MaSua { get; set; }
        public int SoLuongBan { get; set; }
        public int DonGiaBan { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPhamSua SanPhamSua { get; set; }
    }
}
