//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_64131375.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamSua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPhamSua()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
        }
    
        public string MaSua { get; set; }
        public string TenSua { get; set; }
        public string MoTa { get; set; }
        public string AnhSua { get; set; }
        public int SoLuong { get; set; }
        public string HanSuDung { get; set; }
        public int DonGia { get; set; }
        public string MaLoaiSua { get; set; }
        public string MaNCC { get; set; }
        public string MaHSX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual LoaiSua LoaiSua { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
